# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Runs a single command using the runners shell
    - name: Install
      run: npm ci
    - name : copy env
      run:  cp ./src/environments/environment.prod.ts ./src/environments/environment.ts 
    - name: build
      run : npm run-script build
      env : 
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        RECAPCHA_KEY: ${{ secrets.RECAPCHA_KEY }}
    - name: deploy to firebase
      uses : w9jds/firebase-action@master
      with:
          args: deploy --only hosting:djjam-staging 
      env: 
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }};
